In [8]:
import pandas as pd

#Creando Diccionario
Data = {'Measurement': [1, 2, 3 ,4 ,5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 
                        25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
        'Length':[1.118, 1.262, 1.118, 0.480, 1.014, 0.955, 0.978, 0.972, 1.190, 1.055, 0.886, 1.071, 0.861,
                  1.055, 0.834, 1.106, 0.912, 0.773, 0.958, 1.152, 1.324, 2.192, 0.779, 0.692, 1.036, 1.618, 
                  1.187, 0.884, 0.858, 1.269, 0.811, 0.811, 0.636, 0.710, 0.675, 0.830]
        }

print(Data)

{'Measurement': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36], 'Length': [1.118, 1.262, 1.118, 0.48, 1.014, 0.955, 0.978, 0.972, 1.19, 1.055, 0.886, 1.071, 0.861, 1.055, 0.834, 1.106, 0.912, 0.773, 0.958, 1.152, 1.324, 2.192, 0.779, 0.692, 1.036, 1.618, 1.187, 0.884, 0.858, 1.269, 0.811, 0.811, 0.636, 0.71, 0.675, 0.83]}

In [9]:
#Pandas Statistics
#Diccionario a DataFrame
df = pd.DataFrame(Data)

df.head(40)

    Measurement  Length
0             1   1.118
1             2   1.262
2             3   1.118
3             4   0.480
4             5   1.014
5             6   0.955
6             7   0.978
7             8   0.972
8             9   1.190
9            10   1.055
10           11   0.886
11           12   1.071
12           13   0.861
13           14   1.055
14           15   0.834
15           16   1.106
16           17   0.912
17           18   0.773
18           19   0.958
19           20   1.152
20           21   1.324
21           22   2.192
22           23   0.779
23           24   0.692
24           25   1.036
25           26   1.618
26           27   1.187
27           28   0.884
28           29   0.858
29           30   1.269
30           31   0.811
31           32   0.811
32           33   0.636
33           34   0.710
34           35   0.675
35           36   0.830

In [10]:
#Estadísitica Descriptiva con Pandas
print(df.describe())

       Measurement     Length
count    36.000000  36.000000
mean     18.500000   1.001722
std      10.535654   0.301851
min       1.000000   0.480000
25%       9.750000   0.825250
50%      18.500000   0.965000
75%      27.250000   1.118000
max      36.000000   2.192000

In [11]:
#Creación de nuevas variables por columna
Measurement=[]
Length=[]

for i in range(len(df)-1):
  Measurement.append(df.Measurement[i])
  i+=1
print(Measurement)

for i in range(len(df)-1):
  Length.append(df.Length[i])
  i+=1
print(Length)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]
[1.118, 1.262, 1.118, 0.48, 1.014, 0.955, 0.978, 0.972, 1.19, 1.055, 0.886, 1.071, 0.861, 1.055, 0.834, 1.106, 0.912, 0.773, 0.958, 1.152, 1.324, 2.192, 0.779, 0.692, 1.036, 1.618, 1.187, 0.884, 0.858, 1.269, 0.811, 0.811, 0.636, 0.71, 0.675]

In [12]:
from statistics import mean, median, mode, stdev, variance, quantiles

#Measurement Statistics
print("Measurement")
print("Mean=",mean(Measurement))
print("Median=",median(Measurement))
print("Mode=",mode(Measurement))
print("StDev=",stdev(Measurement))
print("Variance=",variance(Measurement))
print("Quantiles=",quantiles(Measurement))

Measurement
Mean= 18
Median= 18
Mode= 1
StDev= 10.246950765959598
Variance= 105
Quantiles= [9.0, 18.0, 27.0]

In [13]:
#Length Statistics
print("Length (m)")
print("Mean=",mean(Length))
print("Median=",median(Length))
print("Mode=",mode(Length))
print("StDev=",stdev(Length))
print("Variance=",variance(Length))
print("Quantiles=",quantiles(Length))

Length (m)
Mean= 1.0066285714285714
Median= 0.972
Mode= 1.118
StDev= 0.30479801274192814
Variance= 0.09290182857142859
Quantiles= [0.811, 0.972, 1.118]